version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27018:27017"  # Map host port 27018 to container port 27017
    volumes:
      - mongo-data:/data/db

  contacts-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/contactbook
    volumes:
      - .:/usr/src/app
    command: npm run dev

volumes:
  mongo-data: